openapi: "3.0.0"

info:
  title: Hello World
  version: "1.0"
servers:
  - url: http://localhost:9090/v1.0

paths:
  /greeting:
    post:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: hello.post_greeting
      requestBody:
        description: "Message containing name"
        required: true
        content:
          applicaton/json:
            schema:
              $ref: '#/components/schemas/HelloMessage'
      responses:
        200:
          description: greeting response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloMessage"

components:
  schemas:
    HelloMessage:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: fluffy
